spring:
  datasource:
    url: jdbc:mysql://localhost:3306/livrosja?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: roots

  flyway:
    enabled: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  jackson:
    default-property-inclusion: non_null

jwt:
  secret:  b9b60f4e-3bcf-4e85-9773-8d2725faae1c
