spring:
  profiles:
    active: dev

  flyway:
    enabled: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  jackson:
    default-property-inclusion: non_null

jwt:
  secret:  b9b60f4e-3bcf-4e85-9773-8d2725faae1c
